export function EventsOn(eventName: string, callback: (...args: any[]) => void): void;
export function EventsOff(eventName: string): void;
export function EventsEmit(eventName: string, ...args: any[]): void;
export function LogPrint(message: string): void;
export function LogDebug(message: string): void;
export function LogInfo(message: string): void;
export function LogWarning(message: string): void;
export function LogError(message: string): void;
export function LogFatal(message: string): void;
export function WindowReload(): void;
export function WindowSetTitle(title: string): void;
export function Environment(): Promise<{ [key: string]: string }>;
